git mv "./benchmark/project-sekai-ctf/sekaictf-2023/crypto/noisier-crc" "./bench/project-sekai-ctf_sekaictf-2023_crypto_noisier-crc"
git mv "./benchmark/project-sekai-ctf/sekaictf-2023/misc/just-another-pickle-jail" "./bench/project-sekai-ctf_sekaictf-2023_misc_just-another-pickle-jail"
git mv "./benchmark/project-sekai-ctf/sekaictf-2023/web/chunky" "./bench/project-sekai-ctf_sekaictf-2023_web_chunky"
git mv "./benchmark/project-sekai-ctf/sekaictf-2023/pwn/network-tools" "./bench/project-sekai-ctf_sekaictf-2023_pwn_network-tools"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/crypto/[Very Easy] Primary Knowledge" "./bench/hackthebox_cyber-apocalypse-2024_crypto_[Very Easy] Primary Knowledge"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/crypto/[Medium] Partial Tenacity" "./bench/hackthebox_cyber-apocalypse-2024_crypto_[Medium] Partial Tenacity"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/crypto/[Very Easy] Dynastic" "./bench/hackthebox_cyber-apocalypse-2024_crypto_[Very Easy] Dynastic"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/forensics/[Very Easy] It Has Begun" "./bench/hackthebox_cyber-apocalypse-2024_forensics_[Very Easy] It Has Begun"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/forensics/[Very Easy] Urgent" "./bench/hackthebox_cyber-apocalypse-2024_forensics_[Very Easy] Urgent"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/misc/[Medium] Were Pickle Phreaks Revenge" "./bench/hackthebox_cyber-apocalypse-2024_misc_[Medium] Were Pickle Phreaks Revenge"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/pwn/[Very Easy] Delulu" "./bench/hackthebox_cyber-apocalypse-2024_pwn_[Very Easy] Delulu"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/reversing/[Very Easy] PackedAway" "./bench/hackthebox_cyber-apocalypse-2024_reversing_[Very Easy] PackedAway"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/reversing/[Easy] Crushing" "./bench/hackthebox_cyber-apocalypse-2024_reversing_[Easy] Crushing"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/reversing/[Hard] FlecksOfGold" "./bench/hackthebox_cyber-apocalypse-2024_reversing_[Hard] FlecksOfGold"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/crypto/MissingBits" "./bench/LosFuzzys_GlacierCTF2023_writeups_crypto_MissingBits"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/crypto/SLCG" "./bench/LosFuzzys_GlacierCTF2023_writeups_crypto_SLCG"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/crypto/WalkingToTheSeaSide" "./bench/LosFuzzys_GlacierCTF2023_writeups_crypto_WalkingToTheSeaSide"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/crypto/shuffled-aes" "./bench/LosFuzzys_GlacierCTF2023_writeups_crypto_shuffled-aes"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/intro/skilift" "./bench/LosFuzzys_GlacierCTF2023_writeups_intro_skilift"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/misc/avatar" "./bench/LosFuzzys_GlacierCTF2023_writeups_misc_avatar"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/rev/rpgo" "./bench/LosFuzzys_GlacierCTF2023_writeups_rev_rpgo"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/rev/sop" "./bench/LosFuzzys_GlacierCTF2023_writeups_rev_sop"
git mv "./benchmark/LosFuzzys/GlacierCTF2023_writeups/web/GlacierExchange" "./bench/LosFuzzys_GlacierCTF2023_writeups_web_GlacierExchange"
git mv "./benchmark/project-sekai-ctf/sekaictf-2022/crypto/diffecient" "./bench/project-sekai-ctf_sekaictf-2022_crypto_diffecient"
git mv "./benchmark/project-sekai-ctf/sekaictf-2022/crypto/robust-cbc" "./bench/project-sekai-ctf_sekaictf-2022_crypto_robust-cbc"
git mv "./benchmark/project-sekai-ctf/sekaictf-2022/crypto/ezmaze" "./bench/project-sekai-ctf_sekaictf-2022_crypto_ezmaze"
git mv "./benchmark/project-sekai-ctf/sekaictf-2023/crypto/randsubware" "./bench/project-sekai-ctf_sekaictf-2023_crypto_randsubware"
git mv "./benchmark/project-sekai-ctf/sekaictf-2023/web/frog-waf" "./bench/project-sekai-ctf_sekaictf-2023_web_frog-waf"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/forensics/[Medium] Data Siege" "./bench/hackthebox_cyber-apocalypse-2024_forensics_[Medium] Data Siege"
git mv "./benchmark/hkcert-ctf/CTF-Challenges/CTF-2022/05-motp" "./bench/hkcert-ctf_CTF-Challenges_CTF-2022_05-motp"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/web/[Easy] Labyrinth Linguist" "./bench/hackthebox_cyber-apocalypse-2024_web_[Easy] Labyrinth Linguist"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/reversing/[Very Easy] LootStash" "./bench/hackthebox_cyber-apocalypse-2024_reversing_[Very Easy] LootStash"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/crypto/[Hard] Permuted" "./bench/hackthebox_cyber-apocalypse-2024_crypto_[Hard] Permuted"
git mv "./benchmark/hkcert-ctf/CTF-Challenges/CTF-2022/22-back-to-the-past" "./bench/hkcert-ctf_CTF-Challenges_CTF-2022_22-back-to-the-past"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/web/[Very Easy] Flag Command" "./bench/hackthebox_cyber-apocalypse-2024_web_[Very Easy] Flag Command"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/misc/[Easy] Unbreakable" "./bench/hackthebox_cyber-apocalypse-2024_misc_[Easy] Unbreakable"
git mv "./benchmark/hackthebox/cyber-apocalypse-2024/web/[Medium] LockTalk" "./bench/hackthebox_cyber-apocalypse-2024_web_[Medium] LockTalk"
git mv "./benchmark/project-sekai-ctf/sekaictf-2023/crypto/noisy-crc" "./bench/project-sekai-ctf_sekaictf-2023_crypto_noisy-crc"
git mv "./benchmark/project-sekai-ctf/sekaictf-2023/forensics/eval-me" "./bench/project-sekai-ctf_sekaictf-2023_forensics_eval-me"
git mv "./benchmark/project-sekai-ctf/sekaictf-2022/crypto/failproof" "./bench/project-sekai-ctf_sekaictf-2022_crypto_failproof"